### ISSUE TITLE
Specificity of Kallisto

### ISSUE THREAD

**Issue by shrukane** [pachterlab/kallisto#100]
Hi, I've been using Kallisto-sleuth on a simulated data set and I found that although the sensitivity of Kallisto is quite high the specificity is low. Have you observed the same ? Any suggestions ?
-Shruti

**Comment by lakigigar** [comment]
How are you measuring the sensitivity and specificity?

**Comment by shrukane** [comment]
Hi, I've been measuring sensitivity and specificity by a roc curve of false positives and true positives in simulated human chromosome data sets with varying no of reads. I observed that as my sensitivity was increasing (by using the data set with higher no of reads) the specificity was decreasing.

**Comment by pmelsted** [comment]
The question is then how do you measure true and false positives. If you simulate a read from transcript t1 and kallisto reports in the pseudobam that it aligned to t1,2,3 do you count that as true or false?

In many cases this t1,2,3 is the correct answer since the read(pair) is entirely consistent with the sequence of all of the transcripts, i.e. the difference between the 3 transcripts is somewhere else. If you are strict about labelling this as a false positive pretty much any aligner will be of low specificity.

This is covered on top of page 4 in the preprint http://arxiv.org/pdf/1505.02710v2.pdf

Also, what do you mean exactly by "human chromosome data sets"?

**Comment by shrukane** [comment]
If I am simulating 100 differentially expressed transcripts and detecting 90 out of those 100, then i am calculating sensitivity as 90%. however, i am detecting 120 total transcripts by kallisto-sleuth, out of which 30 were not a part of original simulation, therefore 30 falsely detected by kallisto (specificity). human chromosome term is not imp here. i am simply taking any random chromosome and using that to simulate rna-seq reads.

**Comment by pimentel** [comment]
@shrukane this sounds to me like an issue with `sleuth` rather than `kallisto`. anyway, it depends on a number of different things, but I imagine you are probably running `sleuth_wt` rather than `sleuth_lrt`? The Wald test is much less well calibrated than the likelihood ratio test. Although, I am willing to bet that the rankings are still quite good (they are fairly comparable in the rankings). if you would like to discuss this further, please provide more information about the simulation (perhaps code if you are willing to share) at the sleuth issues tab. thanks!
