### ISSUE TITLE
Index Format

### ISSUE THREAD

**Issue by OrsonMM** [pachterlab/kallisto#127]
Hi !! 
Im Orson

Is possible read the file index generated for - kallisto index, in other format diferent of hex 

I need know what kind of information save the hash table of index. I hope that you can help me. 

Saludos

**Comment by OrsonMM** [comment]
Hi
For example I use these imput:
>gene1
ATACGATCGATCGATAGCTAGCTAGCTAGCTACGATCGATCGTCGATCGATCGATC
>gene2
ATACGATCGATCGATAGCTAACACTGACTACGACTAGCATCGACTAGCTACGATCG
>gene3
CGCTAGCTAGCATCGATGCATCGATCAGTCAGTCAGCTGATCAGCTACTGATCGTC

and part of the output using the command kallisto index is:

0a00 0000 0000 0000 1f00 0000 0300 0000
3800 0000 3800 0000 3800 0000 4e00 0000
0000 0000 d0d2 d8e4 d824 2767 0000 0000
0000 0000 1a00 0000 f02e 2ddb 728e 2d27
0100 0000 0700 0000 1a00 0000 d078 d2d2
.....

I like know the type of information that contain these output file, in the paper is refer a has table.

**Comment by taltman** [comment]
Have you tried the 'kallisto h5dump' command?

**Comment by OrsonMM** [comment]
Hi 
 
Is not a output after to run quant.  Is the output result of index, I need know the index of hash table.

**Comment by pmelsted** [comment]
The index format is binary, and not meant to be used outside of the kallisto format. In fact it is not guaranteed to be consistent across versions (although that hasn't happened since the initial public release). If you really need to read the index, the only way is to use the code.

If you simply want the target de bruijn graph used by the index, it can be extracted using the `inspect` command

`kallisto inspect index --gfa=index.gfa`

will write it to a GFA file format
