### ISSUE TITLE
kallisto error (No such file or directory)

### ISSUE THREAD

**Issue by vikt0rbl** [pachterlab/kallisto#170]
Hi all!

Every time I try to run an analysis with my fastq files in kallisto 0.44 I get this error and the software closes: 

Pre-processing input files
Using AltDatabase/kallisto/0.42.1/PC/bin/kallisto.exe
Running kallisto on: MG_FH_028_S1_L001_001 kallisto failed due to an unknown error (report to altanalyze.org help).
Traceback (most recent call last):
  File "RNASeq.pyc", line 4692, in runKallisto
  File "RNASeq.pyc", line 4777, in importTPMs
IOError: [Errno 2] No such file or directory: u'C:/Users/vbadill/Documents/Kallisto/KO vs rescue///ExpressionInput/kallisto/MG_FH_028_S1_L001_001/abundance.tsv'

I have tried the default parameters, as well as the ones suggested in several tutorials. I have also tried all possible directories, file naming (e.g. sample028_1.fastq.gz , sample028_2.fastq.gz) and different Windows OS.

I have been stuck with this for quite long time, and it would be great if any of you has any suggestion on to solve it.

Victor﻿

**Comment by pmelsted** [comment]
It looks like you are running kallisto inside a workflow. I would suggest looking at the output/log of this workflow in order to find the reason it failed. If you are running this on your machine  you should check that it works when you run it on the command line.

Also if you post on the kallisto-sleuth mailing list you get more feedback, the issues are mostly used for reporting bugs etc.
