### ISSUE TITLE
Failed to build refseq bacterial database

### ISSUE THREAD

**Issue by crarlus** [pachterlab/kallisto#187]
Hi, pseudoalignments are an interesting application for metagenomics. However I failed to build a database based on the current bacterial NCBI refseq database. Here is the output:
```
time kallisto index -i kallisto_bacteria.db bacteria.*
...
[build] loading fasta file bacteria.997.1.genomic.fna.gz
[build] loading fasta file bacteria.998.1.genomic.fna.gz
[build] loading fasta file bacteria.999.1.genomic.fna.gz
[build] k-mer length: 31
[build] warning: clipped off poly-A tail (longer than 10)
        from 4495 target sequences
[build] warning: replaced 480036795 non-ACGUT characters in the input sequence
        with pseudorandom nucleotides
[build] counting k-mers ... terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted

real    3048m12.942s
user    3003m44.584s
sys     23m0.972s

```
Note also that it took 50 hours to get there.
I am using the latest bioconda version of kallisto (kallisto 0.44.0).

* Is this scenario actually a feasible application for kallisto?
* Is there a way to speed up the indexing?

Thanks,
Carlus

**Comment by mschilli87** [comment]
Looks like you are running out of memory. How big is the reference? What kind of system are you running this on?

**Comment by crarlus** [comment]
Hi,
thanks for your help.
We have a 100-core server with 2 TB of RAM.

The database is 125 GB (compressed), so it is actually possible that the memory is not sufficient. 
But that would mean that kallisto does not work for microbial metagenomics?

**Comment by mschilli87** [comment]
`kallisto` is usually used to index transcriptome. Why I get (and like) the idea of treating genomes like transcripts of a metagenome this could be too much data to handle. Do you use DNA- or RNA-seq data?
In the latter case you couls still join all transcriptomes (given they are annotated; otherwise, maybe you can predict genes first) into a meta-transcriptome and see if this gives you a smaller reference (I'm not familiar with bacteria and what fraction of the genome they express).

---
Either way, I don't think this is a bug in `kallisto` and it would probably be better to ask for help at [biostars](https://www.biostars.org) or [biology SO](https://biology.stackexchange.com/).

**Comment by crarlus** [comment]
Hi,
ok, meanwhile I've found out on [metakallisto](https://github.com/pachterlab/metakallisto) that one does not build an entire refseq DB. Rather one uses a pre-filtering program such as mash first and screens species/genera of interest using kallisto with a species specific kallisto database. Hence the database will be much smaller.
