### ISSUE TITLE
How to estimate the read count for genes?

### ISSUE THREAD

**Issue by Kaaaaaai** [pachterlab/kallisto#203]
Hi developer,

I used kallisto to estimate counts with each transcript.
In order to assess the expression of each gene, should I add all transcript reads of each gene or select the transcript with the highest expression? As an example, if  a read can map to transcript A and B, will the count of both be increased by 1 or 0.5? If 1, then add counts together will overestimated gene expression levels.

thanks,
Kai

**Comment by pmelsted** [comment]
The counts of reads are split among transcripts, so that the sum of all transcript read counts is the same as the number of pseudoaligned reads. When aggregating transcript counts at the gene level the effective length of the transcripts should be taken into account. One way to do this is to aggregate using [sleuth](https://github.com/pachterlab/sleuth), either using the software directly or the same method as implemented.
