### ISSUE TITLE
quant error: resource temporarily unavailable

### ISSUE THREAD

**Issue by vllorens** [pachterlab/kallisto#214]
Hi, 
I'm getting a 'resource temporarily unavailable' error when trying to write the bam pseudoalignments file in single-end mode. It's weird since I'm running hundreds of samples in batch and about one third of the samples fail at this stage, while the rest just run fine. I never had this error in paired-end mode.

Version: v0.45.1
Command: `kallisto quant --index $KAL_IDX -o $KAL_OUT --single --pseudobam --bias --threads=8 -l 200 -s 25 $KAL_IN`
Log and error:
```
[quant] fragment length distribution is truncated gaussian with mean = 200, sd = 25
[index] k-mer length: 31
[index] number of targets: 1,049,278
[index] number of k-mers: 641,607,929
[index] number of equivalence classes: 2,267,430
[quant] running in single-end mode
[quant] will process file 1: data/sdx85_norRNA.fastq
[quant] finding pseudoalignments for the reads ... done
[quant] learning parameters for sequence specific bias
[quant] processed 542,678 reads, 343,286 reads pseudoaligned
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 804 rounds
[  bam] writing pseudoalignments to BAM format .. terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
```

I haven't found anything about this error in other issues, do you have any idea of what might be causing it?

**Comment by mschilli87** [comment]
@vllorens: To me this seems likely to be an issue with https://github.com/samtools/htslib rather than kallisto itself. At least on first glance kallisto appears to outsource all the low-level file handling to this library.

Though I didn't see any obvious candidate line that might cause this.

**Comment by pmelsted** [comment]
This error is not coming from htslib, since it's reported through c++. However the error seems to indicate that kallisto is unable to write to a file. It is probably the fact that the number of jobs are overwhelming the server or the filesystem causing it to time out.

You can run it through a debugger, e.g. `gdb` to find out where in the code or which function call, but ultimately this issue cannot be fixed in kallisto.

You might try writing the output to a temporary folder that's on a local disk before moving the final result to a networked file system, but without knowing the exact system used I can't be of more help
