### ISSUE TITLE
A single matching 31-mer is sufficient for pseudo alignment

### ISSUE THREAD

**Issue by ahoenselaar** [pachterlab/kallisto#231]
Due to the way Kallisto ignores k-mers not found in the reference transcriptome, a single matching 31-mer is sufficient to associate a read with a contig even if no other nucleotide in the read matches the reference transcriptome.
A hypothetical 151bp single-ended read
```
[31-mer found in index][...89 bases are skipped...][31-mer not found in index]
```
would count towards a contig based on the initial 31-mer.
It appears that Kallisto pseudo aligns reads with significant errors or reads that stem from unknown transcripts very aggressively.

**Comment by winni2k** [comment]
I think this is expected behavior for kallisto. 31 consecutive bases of match is very unlikely to happen by chance in for example a human transcriptome. kallisto assumes that you have a fairly complete transcriptome reference. Assuming you have a complete reference transcriptome, why would you expect to see a read with a single 31-mer match that is not from the transcript(s) that kallisto matches the read to?

**Comment by sbooeshaghi** [comment]
A single 31mer is sufficient to map a read. For more details please see https://www.nature.com/articles/nbt.3519
