### ISSUE TITLE
Total single cell RNA data without UMIs for kb processing?

### ISSUE THREAD

**Issue by biobenkj** [pachterlab/kallisto#252]
Hi all,

Kallisto|Bustools is our go-to for anything related to single-cell RNA seq processing. We are into a new problem though and that is with total, single-cell RNA-seq that we would love to be able to process with Kallisto and Bustools. Each cell is sequenced quite deeply (~30 M reads per cell and doesn't appear to exhaust complexity either) but does not have any UMIs attached, effectively acting like bulk RNA but in single cells. My question is whether it's possible to do this with the existing kb workflow? If not, what would be a next step or place for me to start? 

Thanks so much for these tools and your time!

**Comment by sbooeshaghi** [comment]
We have a solution in place that we plan on releasing soon, be on the lookout!

**Comment by biobenkj** [comment]
The paper is incredible @sbooeshaghi, congrats! Now I have the next step in the question, is it possible to take kallisto pseudo output (done in batch mode) and take it to BUS format to rake through bustools if I wanted to do something like RNA velocity (assuming I've done the pseudoalignments to the proper index with introns)? 

Thanks again!

**Comment by sbooeshaghi** [comment]
That's a great question, and one which I have thought a bit about. I don't think it makes sense to try and wrangle the resultant pseudalignments into a bus format since you have already quantified with the EM algorithm. I'm thinking (and I have not done this yet) that a possible way to process SMART-Seq and do RNA velocity would be to first quantify each cell with respect to the transcriptome index, then quantify separately with respect to the intron index. If you wanted to do a gene-only analysis then you would aggregate per gene, and for each gene you would have intronic counts and exonic counts. This should result in two matrices of the same shape that can be used for RNA velocity.

**Comment by winni2k** [comment]
> The paper is incredible @sbooeshaghi, congrats! Now I have the next step in the question, is it possible to take kallisto pseudo output (done in batch mode) and take it to BUS format to rake through bustools if I wanted to do something like RNA velocity (assuming I've done the pseudoalignments to the proper index with introns)?
> 
> Thanks again!

@biobenkj any chance you could share the link to the paper here? Or is the paper not available publicly yet? Cheers.

**Comment by sbooeshaghi** [comment]
@winni2k I think they are referring to this paper: 

https://www.biorxiv.org/content/10.1101/2020.03.05.977991v3

and its associated repo:

https://github.com/pachterlab/BYVSTZP_2020

**Comment by winni2k** [comment]
Cheers!
