### ISSUE TITLE
Readthrough transcripts

### ISSUE THREAD

**Issue by jamesboot** [pachterlab/kallisto#308]
Hello,

Not really an issue but interesting... in some recent comparisons we noticed that kallisto tends to report the expression of readthrough transcripts as very high, whilst STAR estimated the expression of these readthrough transcripts as 0 or very low.

We actually had no idea what readthrough transcripts are, nice explanation below. TLDR - adjacent genes in the genome which end up spliced together after transcription forming a fusion.

https://www.ensembl.info/2019/02/11/annotating-readthrough-transcription-in-ensembl/

I realise this is a very niche question/issue - but I was just wondering if you might be able to provide an explanation as to why kallisto estimates the expression of these types fo transcripts as high whilst STAR does not?

Thanks for your time in advance!

**Comment by Yenaled** [comment]
This is possibly due to multimapping. Reads mapping to a transcript within the fusion/read-through transcript will also end up mapping to the fusion/read-through transcript itself. Kallisto uses an EM algorithm to distribute abundances among multimapping reads.
As for STAR, if STAR alignment is quantified using htseq-count, multimapping reads are discarded (explaining why you see zero expression).
