### ISSUE TITLE
libhdf5.so.10: cannot open shared object file

### ISSUE THREAD

**Issue by Cindy0805** [pachterlab/kallisto#330]
kallisto: error while loading shared libraries: libhdf5.so.10: cannot open shared object file: No such file or directory

I am wondering if anyone had this error and how did you solve it?

There was an old post on the similar issue, but was solved. 
https://github.com/pachterlab/kallisto/issues/39

thanks!

**Comment by mschilli87** [comment]
@Cindy0805: What kind of system are you on and how did you install kallisto?

**Comment by Cindy0805** [comment]
@mschilli87 Hey! I am using Ubuntu 20.04 and I installed Kallisto via conda (https://anaconda.org/bioconda/kallisto).
should i install it using the Source file then?

My conda installed kallisto was wroking fine untill I reinstalled my miniconda and all related tools. In between, I also did some system updates..

**Comment by mschilli87** [comment]
I am not a conda user but to me this sounds like an installation issue. Did you try uninstalling kallisto via conda? If it is not working starting from a clean state, I would assume you are much better off asking for help on the conda support channels or contacting the corresponding maintainer rather than the developers of kallisto. Kallisto requires HDF5 to run, so you are (or in this case conda is) in charge of doing so before you install (and run) kallisto. If you do find a solution, please share it here in case others have the same problem. If you don't get it sorted out by next week, feel free to ping me here again and provide the exact commands you ran to install conda and in turn kallisto. I'll have access to an Ubuntu 20.4 system next week so at least I could try to reproduce your issue. Good luck.

**Comment by Cindy0805** [comment]
Hi, thanks for your suggestion. I reinstalled my conda and kallisto, everything works fine now!

**Comment by mschilli87** [comment]
Glad to hear. Do you mind closing this issue then? :wink:
