### ISSUE TITLE
how to gain raw counts for each gene ?

### ISSUE THREAD

**Issue by zhoudreames** [pachterlab/kallisto#373]
I want to calculate the raw counts of the ASMTL_SSCX gene, can I follow the following steps to gain it?
```
Transcpript     Gene      length    eff_length est_counts TPM
transcript:TCONS_00149762.p1331980    ASMTL_SSCX      3817    3985.55 1801.28 17.8381
transcript:TCONS_00152011.p1231412      ASMTL_SSCX      2390    2314.62 40.7929 0.695597
transcript:MSTRG.49992.3.p343468        ASMTL_SSCX      1009    793.277 4.0628  0.202141
transcript:TCONS_00151182.p87938        ASMTL_SSCX      1293    1131.26 53.0941 1.85241

```
est_counts[Trans1]*(eff_length[Trans1]/length[Trans1])+...+est_counts[Trans4]*(eff_length[Trans4]/length[Trans4])：
1801.28*(3985.55/3817)+40.7929*(2314.62/2390)+ 4.0628*(793.277/1009 )+53.094*(1131.26/1293)=1969.973≈1970

**Comment by Yenaled** [comment]
I don't think that will work. The first transcript in your table is the longest one but you are multiplying it by 3985.55/3817 (which is 1.04) while the third transcript in your table is the shortest one but you are multiplying it by 793.277/1009 (which is 0.786). Longer transcripts tend to be sampled more so those counts should be downweighted (rather than increased) and the opposite is true for shorter transcripts.

I'm also not sure what the mathematical or biological justification is for using the ratio of the effective length to the length.

Ideally, you'd sum up the TPMs and just use the TPMs or you'd use a package like tximport which gives you more accurate gene-level 'raw' counts from the transcript-level counts.

**Comment by mschilli87** [comment]
Alternativeley, you might be able to count the raw reads pseudoaligning to the gene's region from the SAM output generated by [`kallisto quant`'s `--pseudobam` option](https://pachterlab.github.io/kallisto/pseudobam.html).

**Comment by JSSaini** [comment]
@mschilli87 Thank you for your great suggestion.  Would there still be a bias as longer genes would have more transcripts aligned? Does kallisto do some normalization if you give input of genes with coordinates (gff) rather than genome and get the counts of transcripts matched? 
I have concatenated gene files belonging to the list of genomes, and I would infer which genes are more active by matching them to parallel transcriptomics data. @Yenaled  Please help.
