### ISSUE TITLE
IDT Targeted Quantification

### ISSUE THREAD

**Issue by pintoa1-mskcc** [pachterlab/kallisto#378]
Hello,

I have IDT targeted RNAseq results which I quantified with Kallisto using hg19 cDNA FASTA file and importing to R with `tximport.` Upon analysis I found that there are several off-target genes which have significant quantification, some even being found to be differentially expressed. Given this, what would be the best approach for analysis? We have thought of three paths forward:

1. We can filter the resulting abundance results to only the IDT transcripts prior to differential analysis. This means we still pseudoalign to all cDNA, but filter transcripts that are off-target prior to `tximport`. 
2. make a IDT specific FASTA file and requantify the results. This would mean we pseudoalign only to the IDT targeted transcripts
3. Keep original results, assume that we have significant off-target genes with high expression

**Comment by Yenaled** [comment]
Off-target gene quantification can arise if the target capture was not completely efficient. What makes most sense to me is number 3. If you really want to say "ok, I'm considering every target outside my target list to be background", then I recommend using a filter.

In our forthcoming version of kallisto: https://github.com/pachterlab/kallisto-D -- we do have such an option. Basically, create a FASTA with your targets, and create another FASTA with everything you might see outside your targets (supply this option to the --d-list option when running kallisto index), then create that index and run kallisto quant with that. This will be more-or-less like going through the FASTQ file and tossing out the off-target reads.

Number 1 might be suboptimal because the EM algorithm (used to get you probabilistic estimated counts and TPMs) would have used all transcripts in the index.

Number 2 might not be ideal because some reads that shouldn't map to the targeted sequences might end up mapping there (e.g. what if a k-mer from an off-target sequence appears in somewhere in your small/targeted index).

In any case, I still think number 3 can give you the most valuable info (when there are off target things in your sequences, wouldn't you want to observe it?).

**Comment by pintoa1-mskcc** [comment]
So filtering prior to differential would be "best" if I only care about my on target? I'd let tximport count those off targets, then filter post import?

**Comment by Yenaled** [comment]
Yes, you can do that (post-quantification and prior-to-differential) and that would be fine.

**Comment by pintoa1-mskcc** [comment]
Thank you!
