### ISSUE TITLE
Illegal instruction error when running kallisto index

### ISSUE THREAD

**Issue by nadjano** [pachterlab/kallisto#399]
Hello,

When I run `kallisto index (kallisto=0.50.0) -i index.idx transcriptome.fasta` I immediatly get the error `Illegal instruction`. With kallisto=0.48.0 the index building is successful and seems to be fine.
Do you have an idea what the problem could be? 
Thank you! 😄 

Bests,
Nadja

**Comment by Yenaled** [comment]
A few questions:

1. Where did you obtain/install kallisto 0.50.0 from? (was it a pre-built binary? did you compile from source?)
2. Take the first 20 or so lines of transcriptome.fasta -- does kallisto index still fail on that?
3. If possible, can you email me transcriptome.fasta (my email is in my github profile) so I can see if it works on my end?

**Comment by Yenaled** [comment]
Thanks! It seems to work fine on my end; what operating system are you using?

**Comment by Hyeyeonggg** [comment]
Same issue here.

**Comment by Hyeyeonggg** [comment]
> Same issue here.

oh, I solved this problem.
` conda update -n base -c defaults conda `
conda update was the solution!

**Comment by nadjano** [comment]
Thanks a lot @Hyeyeonggg and @Yenaled!
 Updating Conda also solved the issue for me

**Comment by Yenaled** [comment]
Can you describe the error message for running kallisto 0.50.0? I may need to regenerate the binaries in that case.

**Comment by ruochiz** [comment]
I had the same issue. The Illegal instruction (core dumped) error happens when trying to install. I'm using 0.50.0

**Comment by Yenaled** [comment]
Thanks! Seems like the binary is not compatible with all OS's. I'll look into it more -- for now, if conda (after upgrading) or the released binary doesn't work, just compile from source (which is pretty easy for 0.50.0 -- just requires running cmake, make, make install).

**Comment by akkornel** [comment]
Hi @Yenaled, good afternoon!  I encountered this issue at our site, via Bioconda, and I managed to figure out what the problem is: I think the Kallisto release was built on a machine whose CPUs support AVX-512 CPU instructions.  I think the same thing happened for the Bioconda package.

When a CPU encounters AVX-512, if it doesn't recognize the instruction, it raises an "Illegal Instruction" signal, and the program dies as a result.  In the [bioconda-recipes](https://github.com/bioconda/bioconda-recipes) issue, I went into detail on how I tracked down the problem.

The fix is going to revolve around busco, and its build flags.  But as I mention in the bioconda-recipes issue, I don't know what exactly is the best path forward.  Maybe ensure the `COMPILATION_ARCH` and `ENABLE_AVX2` flags can be set when building Kallisto, and pass them through to busco?  And then maybe ensure releases are built with at least `-DENABLE_AVX2=OFF`?

**Comment by akkornel** [comment]
Pinging @mjsteinbaugh as the recipe maintainer.

**Comment by Yenaled** [comment]
Thanks!! That's super useful to know. Setting those compilation flags to off would probably be best -- I'll discuss with Páll Melsted when we make our next release (coming very soon). The architecture specific instructions optimizes performance but increases cross-compatibility issues.

Those flags can be set by first building bifrost (in ext/bifrost) and then having kallisto use that built version of bifrost.

**Comment by mschilli87** [comment]
Is there any new development? I hit the same issue trying to index a transcriptome using kallisto index v.0.51.1 installed from bioconda on some older hardware. Is there really no option to use modern kallisto on legacy clusters, like they are commonly used at universities, other than building it from source? I share my pipeline with other, less experienced users via snakemake workflows that pull in depenencies via conda. Polars has the same issue, but there is a legacy cpu recipe available that can be used instead to trade some performance for greater portability.
I would rather spend time on upstreaming a solution that works for other users and future versionsof kallisto than special-casing around kallisto with a custom build that won't be required in most environments.

Also, may I ask why this issue is closed, when the latest comments clearly indicate this is (or at least was at the time) an ongoing problem? It was rather hard to track my crash to this issue.

**Comment by Yenaled** [comment]
The issue was considered resolve because setting the cmake flags fixes the issue.

You could download the binaries from the releases page on GitHub — there are some there that don’t contain the optimizations and should work on legacy machines.

**Comment by mschilli87** [comment]
Thank you. I will give that a try then. If it works, I will try to get those into bioconda (similar to how conda-forge has handled this issue for Polars) so I (and others) can define their enviroments via conda. But that's not a kallisto issue then. So thank you again for the fast response.

---
PS: `kallisto_linux-v0.51.1_optoff_k64` from [`kallisto_LongKmer_NoOpt-v0.51.1.tar.gz`](https://github.com/pachterlab/kallisto/releases/download/v0.51.1/kallisto_LongKmer_NoOpt-v0.51.1.tar.gz) did the trick for me indeed.

**Comment by mschilli87** [comment]
@Yenaled: Sorry to bother you again, but when I tried fixing this issue over on bioconda I realized that their cmake options already match the ones I found for your `*_optoff_k64` builds: https://github.com/pachterlab/kallisto/blob/4e9f29cf3b021260415430c057a22469ca081391/.make_binaries.sh#L63
See https://github.com/bioconda/bioconda-recipes/issues/42633#issuecomment-3830650449 for details.
Would you mind sharing the exact commands you used to build `kallisto_linux-v0.51.1_optoff_k64` (which works for me) and/or having a look at [bioconda's `kallisto/build.sh`](https://github.com/bioconda/bioconda-recipes/blob/6bcc19287bb7f99a10c237c3024134780f20ae68/recipes/kallisto/build.sh) to help me figure out why their binary doesn't work for me?

**Comment by Yenaled** [comment]
That file you linked to contains the _exact_ commands I used to build that binary, with some hacks at the top to force static linking of zlib/hdf5 to get it to compile under a cross-compilation docker.

The bioconda is building it with _x86-64-v3_ specified (which I know supports AVX2 instruction sets) and might force it to compile a certain way designed only for newer systems (I'm not a systems expert admittedly), which would lead to SIGILL.

**Comment by mschilli87** [comment]
I found some time to further dig into what's going on there and traced it to a build failure (using the conda recipe's build script) on the legacy CPU system while configuring `ext/htslib`:

```
configure:3243: ./conftest
./conftest: CPU ISA level is lower than required
```

Note that this can be reproduced even if changing the build script to use plain `x86-64` rather than `x86-64-v3`.

So my current best guess is that the (bundled) htslib dependency does not support pre-x86-64-v3 arches in a hardcoded way. However, as @Yenaled's binaries *do* work on that very same system, I was wondering if there are differences in how that dependency is build.

**Comment by mschilli87** [comment]
@Yenaled: FYI: I finally figured it out: https://github.com/bioconda/bioconda-recipes/pull/69183
The `htslib` failure was a red herring caused by `stdlibc` used by `conda` itself requiring v3 instructions.
This was unrelated to any package involved here but due to the fact that I tried to build on the same machine I encountered the error on and as I don't have docker permissions on that machine was not able to reproduce the exact build environment used by bioconda's CI.
In the end it was a global `--march` set unconditionally for any Linux_64 build in `bioconda's` `kallisto` recipe. I removed that one, opened a draft PR to trigger building on bioconda's CI rather than my local machine (to avoid the `stdlibc` related issues), downloaded the build artifacts and installed from that local channel - Now I can finally run `kallisto` installed via `conda` on my legacy machine.
I hope this will get merged soon, but I wanted to let you know so you don't spend time on it anc can tell other users that might reach out to you before my PR gets merged.
Also, thank you for pointing me in the right direction, once I realized the `htslib` thing was unrelated, you last comment helped me to very quickly identify the actual root cause.
