### ISSUE TITLE
Windows release not available for v0.50.1

### ISSUE THREAD

**Issue by GuyTeichman** [pachterlab/kallisto#416]
Hi,
It looks as if a Windows release was not included in the most recent release (v0.50.1) assets. Thanks!

**Comment by Yenaled** [comment]
That is correct. I am having trouble making a windows binary (it requires very specific modifications because some of the code will just not compile on windows unless edited... also doesn't help that I don't actually own a windows machine).

As soon as I (or one of my collaborators) is able to generate a windows binary, it will be added to the release immediately.

P.S. I recommend using WSL2 when working on windows.

**Comment by Yenaled** [comment]
windows binary is now available (thanks to the wonderful Páll Melsted!)
