### ISSUE TITLE
Using kb to match the output of kallisto pseudo?

### ISSUE THREAD

**Issue by stiv1n** [pachterlab/kallisto#423]
There is discrepancy between the results produced by kallisto v0.46 and the kb (kallisto v0.50.1).

Context:
The goal is quantify Repetitive element transcripts. The sequences are provided as unique transcript to gene mappings in t2g. So theoretically gene-level output of kb should match the transcript-level output of kallisto 0.46.
kallisto pseudo overwhelmingly performs better in a simulated benchmark. However, I have encountered multiple "core dumped" issues with kallisto pseudo. 
And, naturally, I want to be  able to use the latest version. 

Parameter scheme:
```
kallisto pseudo --quant -i ../../reference/index.idx -o ../../data/SMARTseq/out/ -b ../../data/SMARTseq/smart-seq_batch.txt -t 16
kb count -i ../../reference/index.idx  -o ../../data/SMARTseq/out/ -t 16 -x SMARTSEQ2 --parity=paired \
     -g t2g.txt -w none  --mm ../../data/SMARTseq/smart-seq_batch.txt
```

Is there a way to use the latest version of Kallisto (kb) to match the results of kallisto pseudo?

**Comment by Yenaled** [comment]
They should give near-identical results, however, you're not running in them in an apples-to-apples comparison.

You're running kb count with the --mm option rather than using the transcript-level EM algorithm. You should run kb count with the --tcc option instead.

See the PDF of the latest preprint https://doi.org/10.1101/2023.11.21.568164 - for documentation.

Also, how are you generating the reference for both 0.46.0 and 0.50.1? There are differences in reference generation between using "kb ref" and 0.46.0's "kallisto index".

**Comment by stiv1n** [comment]
Thanks for the fast response!

Index is build for both cases with the corresponding kallisto version:
```
kallisto index  -i index custom.fasta
```
From the manuscript:
"The procedure to generate transcript-level abundance matrices is performed by running the kallisto quant-tcc command on the TCC matrices."
This will allow me to compare apples to apples. 
Can I run  `quant-tcc` as part of the kb count run?

**Comment by Yenaled** [comment]
Per my response above, use --tcc within kb count. That automatically invokes kallisto quant-tcc.

**Comment by stiv1n** [comment]
You are correct! It does invoke it in the last step.
