### ISSUE TITLE
Error encountered when quantifying single-end reads with zero variance

### ISSUE THREAD

**Issue by MohHallal** [pachterlab/kallisto#429]
Hello,

I attempted to use both kallisto 0.50.1 and kallisto 0.46.2 to quantify single-end reads. All my reads have a length of 76, resulting in zero variance. Thus, when I include --single -l 76 -s 0 in my command, I encountered the following error messages:

"Error: cannot supply mean/sd without supplying both -l and -s
Error: fragment length mean and sd must be supplied for single-end reads using -l and -s"

However, substituting -s 1 instead of -s 0 resolved the issue, allowing the command to execute normally. I'm curious if this is an internal issue and whether it might affect the accuracy of my results. 

Thank you for your attention to this matter.

**Comment by pmelsted** [comment]
The length distribution refers to the fragment length, not the sequenced read. The distribution cannot be inferred from the data like with paired end reads so it must be supplied. 

The distribution may have been measured while doing library prep and you can use that information, otherwise I would recommend using common values like -l 200, -s 50

**Comment by MohHallal** [comment]
Thank you for the the quick clarification, I appreciate it. Have a good day!
