### ISSUE TITLE
Support for SMART-Seqv4

### ISSUE THREAD

**Issue by cakeinspace** [pachterlab/kallisto#439]
Hello thanks for the wonderful tool. I was wondering if there is support for smart-seq-v4 for any plans to add support for it.

Thanks in advance 
Anurag

**Comment by Yenaled** [comment]
There are no plans for a simple -x SMARTSEQ4 option, because the number of sequencing technologies is increasing more rapidly than I can handle and I simply don't have the time to look into the optimal way to process each new technology that comes out (especially if the locations of the barcodes, UMIs, etc. are non-trivial to parse).

However, kallisto is a very flexible tool so there will almost certainly exist a way to process smart-seq v4 data with the features that already exist in kallisto. All one needs to be given is the barcode+umi location and length, the location and length of other technical sequences (adapters, special tags, etc.), the "on list" of barcodes, etc.

**Comment by cakeinspace** [comment]
thanks a lot
