### ISSUE TITLE
Read BAM files

### ISSUE THREAD

**Issue by sjackman** [pachterlab/kallisto#46]
My site (and I believe others) do not store the FASTQ file, only the BAM file.

**Comment by pmelsted** [comment]
There is not a lot of agreement on what to store in the BAM file for RNA-Seq. Some do multimapping of reads where each read/alignment has one entry as is common of input to express and rsem. Others may have sorted by genomic coordinates so this tears the reads apart.

In any case we believe this is best solved by other programs and the user that knows their data better.

kallisto can also read from process substitution, so that helps with scriptability.

**Comment by sjackman** [comment]
> kallisto can also read from process substitution

That's good to know.
