### ISSUE TITLE
Estimated Counts Different From Pseudobam Read Counts

### ISSUE THREAD

**Issue by davebridges** [pachterlab/kallisto#67]
I am a bit confused with the meaning of estimated counts.  I aligned my (single ended) reads to a transcriptome and generated a pseudobam file.  Based on samtools flagstat this was a mapping efficiency of 77% (41335716/53448456), so i cracked open the tsv file and thought the sum of estimated counts should be 41335716, but it is only 20717104, close to half as many.  The relevant options are ` --single -l 174 -b 100 -t 8 --pseudobam`.  Why doesn't the mapped reads in the pseudobam file match the estimated counts?

**Comment by pimentel** [comment]
Estimated counts refers to the number of reads that were estimated after
the deconvolution step. The pseudobam output reports all the possible
mapping a of a read during the pseudoalignment phase. For each read, it can
appear several times in the pseudobam output because it is compatible with
many transcripts. During the deconvolution step the EM algorithm is used to
divide the mass of each read based on the likelihood. Essentially each read
is fractionally assigned to each transcript based off of the assignment
that maximizes the likelihood.

The number of unique read names that have mappings should equal the sum of
estimated counts.

Hope that helps.


Best,

Harold

**Comment by davebridges** [comment]
Thanks Harold,

I think I understand but one thing still isnt clear...

For my run
* Total Reads in fastq file 32829845
* Redundant Mapped Reads 41335716
* Sum of estimated counts 20717104

So does that implicate that the mapping efficiency is 20717104/32829845 63%?  That still isnt quite the 77% implied by the psuedobam file.

**Comment by pmelsted** [comment]
The flagstat tool doesn't count the number of unique reads, but the number of alignments reported. So if a readpair maps to multiple transcripts it is reported for each possible transcript. 

We don't set the secodary flag for the alignments so they don't get reported by flagstat. This is something we'll fix in the next version of kallisto. Even so the percentage computed by flagstat is incorrect, since they don't correct for the number of secondary alignments.

To get the number of aligned fragments in the bam file, you can do

```
samtools view -F 4 sam_bam_file | uniq | wc -l
```

since readpairs are adjacent and share the same name, uniq will only count them once.

**Comment by pimentel** [comment]
I think this issue is resolved? Closing for now. If it is not, please reopen it.

Thanks,
Harold
