### ISSUE TITLE
TPM is “-nan”

### ISSUE THREAD

**Issue by flying-sheep** [pachterlab/kallisto#76]
Hi, running the following command with [this reference](http://bio.math.berkeley.edu/kallisto/transcriptomes/Mus_musculus.GRCm38.rel79.cdna.all.fa.gz) index and [this file](https://gist.github.com/flying-sheep/6462174f840b990c138e)

`kallisto quant -i Mus_musculus.GRCm38.rel79.cdna.all.fa.idx -o CAAAG --single -l 100 CAAAG_1.fastq.gz`

results in a abundances.tsv like this:

```tab
target_id	length	eff_length	est_counts	tpm
ENSMUST00000178537	12	12	0	-nan
ENSMUST00000178862	14	14	0	-nan
ENSMUST00000177564	16	16	0	-nan
ENSMUST00000179664	11	11	0	-nan
ENSMUST00000179883	16	16	0	-nan
...
```

is there anything wrong with the input or is this a bug?

**Comment by vals** [comment]
The read file you are using comes from only 5' ends of transcripts. (It's from [this](http://genome.cshlp.org/content/21/7/1160.long) publication). Kallisto assumes reads comes from anywhere in the transcript. Maybe this causes something to go wrong?

**Comment by flying-sheep** [comment]
hmm, I’m using a regex to split off the barcodes, i.e.

```regex
^(?P<bc>.{5})G*(.+?)A*$
```

then i sort all reads by barcodes (you can see here one such file named after a barcode)

this works for [all samples/cell types](http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE21180) except the last one (MEFs). here is an [example file](https://gist.github.com/flying-sheep/597e8497d02ef356d810) of the same barcode in another sample.

interestingly, the working ones all seem to be 50b long and the MEF reads only 35b. another thing to note is that they apparently used 5b barcodes while claiming in the paper they used 6b barcodes.

**Comment by vals** [comment]
Ah it works for the other ones... Then I guess that's not the problem (though I think the expression values you will get will be inaccurate due to how the model is set up).

What if you take one of the working ones and trim down the read to 35b? Just wildly guessing, perhaps it's too ambiguous with such short reads?

**Comment by flying-sheep** [comment]
i tried it, works well. (in other news i now know why autotools is horrible because i installed fastx-toolkit for trimming)

**Comment by pimentel** [comment]
@flying-sheep what version of kallisto are you running?

**Comment by flying-sheep** [comment]
0.42.2.1

i forgot to mention it since it was *too* prominently in my mind, given that this exact version fixed a similar bug

**Comment by pmelsted** [comment]
The -nan values are most likely since nothing aligned, the quant step should report the number of reads pseudoaligned.

It looks like the reads are 26bp long, whereas the index is by default using 31bp, thus kallisto can't pseudoalign anything. With such short reads you might be better off with alignment based solutions.

You can rebuild the index using the `-k 21` parameter to use 21-mers instead, this should get you the results.

**Comment by flying-sheep** [comment]
ah got it!

it would probably make sense for kallisto to return a non-zero exit status and do nothing if the index is bigger than the available reads, right?

**Comment by pimentel** [comment]
@flying-sheep: as @vals pointed out, if the reads only come from 5' ends, then the quantification will not be valid with a default transcriptome. This is due to the fact that our model assumes that reads are distributed across the transcript, not just from one end.

For now I don't think we'll do a non-zero exit status. In the future we might report a non-zero exit if absolutely no reads map.

Closing issue for now.

**Comment by flying-sheep** [comment]
Thanks!

One question for clarification: Why do you not do the exit status thing now but consider it for the future? What changes in the future?
